---
title: "Literature Review"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
fontsize: 12pt
header-includes:
    - \usepackage{setspace}\onehalfspacing
bibliography: "literature/references.bib"
---


This section briefly reviews the state of the literature on voter turnout and what each theoretical framework would say about rainfall's effect on voter turnout. The foundation of theories on voter mobilization is the idea that vote turnout depends on whether the rewards outweigh the costs. The cost benefit analysis is encapsulated in the following equation in which one's rewards from voting, $R$, is expressed as the sum of benefits and costs, 
$$R = PB + D - C$$  
where $P$ is the probability of one's vote being pivotal, $B$ is the perceived benefits from the victory of one's preferred candidate, $D$ is one's perceived benefits from fulfilling civic duty, and $C$ is the private and material costs of voting. Because $P$ is assumed to be small for majority of the voters, the literature has mainly developed by identifying factors that go into $B$, $D$, and $C$. For instance, the social-economic status (SES) model posits that those with low socio-economic status are limited in personal time, energy, and resources to engage in politics and therefore carry a large sized $C$ and a repressed $D$. Political parties may shape a voter's opportunity for political participation, but access to those opportunities are nonetheless conditioned by one's SES. As @leighley1995 rightly notes, although SES variables often turnout to be statistically significant predictors for voter turnout, the model is theoretically unsatisfactory as it considers voting as a private act without paying much attention to the social context that would add additional dimensions to $D$ and $C$. Recent publications consider voting as an act anchored to the actor's social context although researchers differ on exactly what makes the act 'social'. For instance, @gerber2008 claims that rational voters are motivated by peer pressure to vote and therey adding the fear of social sanction to $C$ while @rolfe2012 argues for a more subtle pscyhological mechanism that essentially does away with the above equation. 

According to the orthodox framework of a rational, atomistic voter, rainfall on Election Day, even if at moderate level, could be a minor cost that could nonetheless tip the scale. This is @gomezetal2007's alternative hypothesis against the null hypothesis of null effect. There are other papers that employ the potential cost of exposing oneself to bad weather as an exogenous source of variation to attendance such as @madestam2013 and @rotton2000. However, whether rainfall, i.e. the possibility of getting wet, would constitute an exogenous shock to attendance rate depends on the event in question. For instance, @horiuchietal2009 takes heed to explain that rain is a reasonable source of exogenous shock to voter turnout in Japanese general elections, and it is worth quoting their reasoning to show why the same may be difficult to argue for election in the United States.[^persson]

[^persson]: The other paper that takes the electoral context into consideration is @persson_etal2014, which studies whether rainfall lowers voter turnout in Swedish general elections. Due to the lack of voter registration requirement and the Election Day being on Sunday, the authors expect that rainfall would not constitute a cost to voters.  


> First of all, in Japan, voting typically takes place on Sunday. Therefore, weather conditions affect opportunity cost calculations among citizens--whether or not to go outdoors. ... Second, unlike other democracies where candidates and parties keep on mobilising until polling stations close, neither candidates nor political parties in Japan are allowed to deploy any campaign activity on the polling day. The media are also expected to be neutral (and quiet) until the polling stations close. ... [W]e can safely assume that there is no other systematic political variable on the voting day. Finally, in our panel data there is indeed a substantial variation in the amount of rainfall *within each municipality* across elections [italics in the original]. Unlike elections in the United States, which take place in fixed intervals, the timing of Japan's Lower House elections is not fixed. The prime minister can dissolve the Lower House and call a general election any time before the four-year-term expires (9-10). 

@horiuchietal2009's first reason is persuasive, especially when combined with the fact that it could happen at any time of the year. In the United States, the general and midterm elections for federal public officials are set by law to take place on the first Tuesday after November 1st. Voters can acclimate to wet November if they live in such region, making it their habit to check the weather forecast and prepare their attire for the weather. Moreover, as the authors note, the United States election campaigns start at least an year before. There is an adequate amount of buildup to the election that may make the cost of getting wet negligible. Of course, this sense of buildup may vary significantly from county to county depending on the competitiveness of the race, so it is possible that rain is the minor cost that could determine a voter's turnout decision in less uncompetitive counties (@fraga_hersh2010). Most importantly, however, campaigns do not end until the polls close, and if there is a forecast of rain on Election Day, the campaigns may mobilize their volunteers to carpool or to provide drinks and food to entertain the voters waiting in line.  

We have researched other pscyhological effects that rain may have on voters, but these effects are either a) conditional on a duration of rain rather than rain on one single day, or b) ambivalent on whether they should motivate or deter voter turnout. For example, there is abundant research on whether long duration of bad weather could affect mood, which could affect decision making, but all of these research assume that the effect would only kick in after a duration, not from a single day of bad weather (@hannak2012, @keller2005, @denissen2008, @goetzmann2005). Even if a long duration of rain does depress one's mood, it is not clear whether seasonal rain has the same effect. One might argue that instead of rain, it could be seasonal affective disorder (SAD), which tends to happen during fall and winter. There have been economic research looking into whether SAD explains the low stock returns in the final quarter (@Kamstra_etal2003), but as @jacobsen2003 shows, SAD is probably one of the many things that correlate with the seasonal variable, which if applied our research question would be equivalent to saying that voter turnout is low because the US elections take place in November. 

[--summarizing paragraph to be included--] 

## References